/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kimdo
 */
public class formThongKe extends javax.swing.JFrame {
//    int id= formLogin.id_taiKhoan;
    /**
     * Creates new form formThongKe
     */
    public formThongKe() {
        initComponents();
        showCB();
        CountChuDe();
        CountCauHoi();
        
    }
    private void showCB() {
        List<String> data = DbAccess.findTenBoDe();
        for(String s: data){
            cbBoDe.addItem(s);
            cbBoDe2.addItem(s);
            cbBoDe3.addItem(s);
            cbBoDe4.addItem(s);
            cbBoDe5.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDeThi = new javax.swing.JButton();
        btnDAngXuat = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbBoDe = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbDiemCaoNhat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbBoDe2 = new javax.swing.JComboBox<>();
        btnAvg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbDiemTrungBinh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbBoDe3 = new javax.swing.JComboBox<>();
        btnCount = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbCount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbBoDe4 = new javax.swing.JComboBox<>();
        btnCount1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbCount1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbBoDe5 = new javax.swing.JComboBox<>();
        btntaikhoan = new javax.swing.JButton();
        cbTen = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnCountDeThi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCountCauHoi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Người dùng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 119, 52));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Thống kê");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 119, 52));

        btnDeThi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDeThi.setText("Đề thi");
        btnDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeThiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 119, 53));

        btnDAngXuat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDAngXuat.setText("Đăng xuất");
        btnDAngXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDAngXuatActionPerformed(evt);
            }
        });
        getContentPane().add(btnDAngXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 119, 56));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Thi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 119, 52));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Điểm số cao nhất của mỗi bộ đề :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 227, -1));

        cbBoDe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbBoDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------" }));
        cbBoDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBoDeMouseClicked(evt);
            }
        });
        getContentPane().add(cbBoDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 271, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Thống kê");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 88, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Điểm :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        lbDiemCaoNhat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbDiemCaoNhat.setText("0");
        getContentPane().add(lbDiemCaoNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 28, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Điểm số trung bình của  mỗi bộ đề :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 213, -1));

        cbBoDe2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbBoDe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------" }));
        cbBoDe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBoDe2MouseClicked(evt);
            }
        });
        getContentPane().add(cbBoDe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 271, -1));

        btnAvg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAvg.setText("Thống kê");
        btnAvg.setEnabled(false);
        btnAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvgActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 88, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Điểm :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        lbDiemTrungBinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbDiemTrungBinh.setText("0");
        getContentPane().add(lbDiemTrungBinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 50, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Số người đã làm bộ đề ( mỗi  tài khoản chỉ tính 1 lần) :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 304, -1));

        cbBoDe3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbBoDe3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------" }));
        cbBoDe3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBoDe3MouseClicked(evt);
            }
        });
        getContentPane().add(cbBoDe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 271, -1));

        btnCount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCount.setText("Thống kê");
        btnCount.setEnabled(false);
        btnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountActionPerformed(evt);
            }
        });
        getContentPane().add(btnCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 88, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Số người :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 65, -1));

        lbCount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbCount.setText("0");
        getContentPane().add(lbCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 25, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Số lần bộ đề đã được làm :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 271, -1));

        cbBoDe4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbBoDe4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------" }));
        cbBoDe4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBoDe4MouseClicked(evt);
            }
        });
        getContentPane().add(cbBoDe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 271, -1));

        btnCount1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCount1.setText("Thống kê");
        btnCount1.setEnabled(false);
        btnCount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCount1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 88, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Số lần :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 46, -1));

        lbCount1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbCount1.setText("0");
        getContentPane().add(lbCount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 25, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Tài khoản có điểm số cao nhất trong mỗi bộ đề :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 276, -1));

        cbBoDe5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbBoDe5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------" }));
        cbBoDe5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBoDe5MouseClicked(evt);
            }
        });
        getContentPane().add(cbBoDe5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 271, -1));

        btntaikhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btntaikhoan.setText("Thống kê");
        btntaikhoan.setEnabled(false);
        btntaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaikhoanActionPerformed(evt);
            }
        });
        getContentPane().add(btntaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 88, -1));

        cbTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbTen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Tổng số đề thi :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 99, -1));

        btnCountDeThi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCountDeThi.setText(" ");
        getContentPane().add(btnCountDeThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 69, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Tổng số câu hỏi :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 110, -1));

        btnCountCauHoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(btnCountCauHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 70, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/phong-nen-xanh-duong.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setSize(new java.awt.Dimension(1084, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        formThongKe frm = new  formThongKe();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeThiActionPerformed
        // TODO add your handling code here:
        formDeThi frm = new  formDeThi();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDeThiActionPerformed

    private void btnDAngXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDAngXuatActionPerformed
        // TODO add your handling code here:
        formLogin frm = new  formLogin();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDAngXuatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        formThi frm = new  formThi();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
             try {
            Socket socket = new Socket("localhost", 8000);
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            String send = "";
            String flag = "8";
            send += flag;
            send += "///";
            send += (String) cbBoDe.getSelectedItem() ;
            send += "///";
            dos.writeUTF(send);
            String receive = dis.readUTF();
            lbDiemCaoNhat.setText(receive);
            socket.close();
        } catch (IOException ex) {
//            Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
                lbDiemCaoNhat.setText("0");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvgActionPerformed
        // TODO add your handling code here:
         try {
            Socket socket = new Socket("localhost", 8000);
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            String send = "";
            String flag = "7";
            send += flag;
            send += "///";
            send += (String) cbBoDe2.getSelectedItem() ;
            send += "///";
            dos.writeUTF(send);
            String receive = dis.readUTF();
            lbDiemTrungBinh.setText(receive);
            socket.close();
        } catch (IOException ex) {
//            Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
                lbDiemTrungBinh.setText("0");
        }
    }//GEN-LAST:event_btnAvgActionPerformed

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
        // TODO add your handling code here:
         try {
            Socket socket = new Socket("localhost", 8000);
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            String send = "";
            String flag = "9";
            send += flag;
            send += "///";
            send += (String) cbBoDe3.getSelectedItem() ;
            send += "///";
            dos.writeUTF(send);
            String receive = dis.readUTF();
            lbCount.setText(receive);
            socket.close();
        } catch (IOException ex) {
//            Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
                lbCount.setText("0");
        }
    }//GEN-LAST:event_btnCountActionPerformed

    private void btnCount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCount1ActionPerformed
        // TODO add your handling code here:
         try {
            Socket socket = new Socket("localhost", 8000);
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            String send = "";
            String flag = "10";
            send += flag;
            send += "///";
            send += (String) cbBoDe4.getSelectedItem() ;
            send += "///";
            dos.writeUTF(send);
            String receive = dis.readUTF();
            lbCount1.setText(receive);
            socket.close();
        } catch (IOException ex) {
//            Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
                lbCount1.setText("0");
        }
    }//GEN-LAST:event_btnCount1ActionPerformed

    private void btntaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaikhoanActionPerformed
        // TODO add your handling code here:
         Connection connection = null;
        Statement statement = null;
        List<String> listTen = new ArrayList<>();;
        String bode = (String) cbBoDe5.getSelectedItem();
             try {
            String URL = "jdbc:sqlserver://NAMHUYNH\\SQLEXPRESS:1433;"+
                    "databaseName=SHAREDETHI;user=sas;password=12345;encrypt=false";
            connection = DriverManager.getConnection(URL);
            String sql = "WITH RankedScores AS (\n" +
"    SELECT TAIKHOAN.TEN, SCORE.SCORE,\n" +
"           DENSE_RANK() OVER (ORDER BY SCORE.SCORE DESC) AS Rank\n" +
"    FROM SCORE\n" +
"    JOIN CHUDE ON SCORE.CHUDE_ID = CHUDE.CHUDE_ID\n" +
"    JOIN TAIKHOAN ON SCORE.TAIKHOAN_ID = TAIKHOAN.TAIKHOAN_ID\n" +
"    WHERE CHUDE.TENCHUDE =  N'"+bode+"'\n" +
")\n" +
"SELECT TEN\n" +
"FROM RankedScores\n" +
"WHERE Rank <= 1;";
            statement = connection.createStatement();           
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {                
                  String name = resultSet.getString("TEN");
                  listTen.add(name);
            }
//                 System.out.println("listTen "+listTen);
            StringBuilder result = new StringBuilder();
            cbTen.removeAllItems();
            for (String item : listTen) {
                cbTen.addItem(item);
                
            }

        } catch (SQLException ex) {
            Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if(statement != null) {
                try {
                    statement.close();
                } catch (SQLException ex) {
                    Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btntaikhoanActionPerformed

    private void cbBoDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBoDeMouseClicked
        // TODO add your handling code here:
        jButton4.setEnabled(true);
    }//GEN-LAST:event_cbBoDeMouseClicked

    private void cbBoDe5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBoDe5MouseClicked
        // TODO add your handling code here:
        btntaikhoan.setEnabled(true);
    }//GEN-LAST:event_cbBoDe5MouseClicked

    private void cbBoDe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBoDe2MouseClicked
        // TODO add your handling code here:
        btnAvg.setEnabled(true);
    }//GEN-LAST:event_cbBoDe2MouseClicked

    private void cbBoDe3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBoDe3MouseClicked
        // TODO add your handling code here:
        btnCount.setEnabled(true);
    }//GEN-LAST:event_cbBoDe3MouseClicked

    private void cbBoDe4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBoDe4MouseClicked
        // TODO add your handling code here:
        btnCount1.setEnabled(true);
    }//GEN-LAST:event_cbBoDe4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                formNguoiDung frm = new  formNguoiDung();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvg;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnCount1;
    private javax.swing.JButton btnCountCauHoi;
    private javax.swing.JButton btnCountDeThi;
    private javax.swing.JButton btnDAngXuat;
    private javax.swing.JButton btnDeThi;
    private javax.swing.JButton btntaikhoan;
    private javax.swing.JComboBox<String> cbBoDe;
    private javax.swing.JComboBox<String> cbBoDe2;
    private javax.swing.JComboBox<String> cbBoDe3;
    private javax.swing.JComboBox<String> cbBoDe4;
    private javax.swing.JComboBox<String> cbBoDe5;
    private javax.swing.JComboBox<String> cbTen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbCount;
    private javax.swing.JLabel lbCount1;
    private javax.swing.JLabel lbDiemCaoNhat;
    private javax.swing.JLabel lbDiemTrungBinh;
    // End of variables declaration//GEN-END:variables
    public void CountChuDe(){
             try {
                 Socket socket = new Socket("localhost", 8000);
                 DataInputStream dis = new DataInputStream(socket.getInputStream());
                 DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
                 String send = "";
                 String flag = "5";
                 send += flag;
                 send += "///";
                 dos.writeUTF(send);
                 String receive = dis.readUTF();
                 btnCountDeThi.setText(receive);
                 socket.close();
             } catch (IOException ex) {
            Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void CountCauHoi(){
        try {
            Socket socket = new Socket("localhost", 8000);
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            String send = "";
            String flag = "6";
            send += flag;
            send += "///";
            dos.writeUTF(send);
            String receive = dis.readUTF();
            btnCountCauHoi.setText(receive);
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(formThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
