CREATE DATABASE [SHAREDETHI]
GO
USE SHAREDETHI
go


CREATE TABLE [TAIKHOAN] (
  [TAIKHOAN_ID] INT IDENTITY(1,1) NOT NULL,
  [EMAIL] VARCHAR(255) NOT NULL,
  [MATKHAU] VARCHAR(255),
  [TEN] VARCHAR(255) DEFAULT NULL,
 -- status TINYINT DEFAULT 1,
  [GIOITINH] TINYINT DEFAULT 0,
  [NGAYSINH] DATETIME NOT NULL DEFAULT GETDATE(),
  [PHANQUYEN] TINYINT DEFAULT NULL,
  [OTP] VARCHAR(20) DEFAULT NULL,
  [NGAYXACNHAN] DATETIME DEFAULT NULL
);
SET IDENTITY_INSERT [TAIKHOAN] ON 
INSERT [TAIKHOAN]([TAIKHOAN_ID],[EMAIL],[MATKHAU],[TEN],[GIOITINH],[NGAYSINH],[PHANQUYEN],[OTP],[NGAYXACNHAN])
VALUES (1,N'kimdong240502@gmail.com',N'huynhnam',N'nam',1,N'2022-01-06',1,12345,null)
INSERT [TAIKHOAN]([TAIKHOAN_ID],[EMAIL],[MATKHAU],[TEN],[GIOITINH],[NGAYSINH],[PHANQUYEN],[OTP],[NGAYXACNHAN])
VALUES (2,N'kimdong240502@gmail.com',N'huynhnam',N'nam',1,N'2022-01-06',1,12345,null)
SET IDENTITY_INSERT [TAIKHOAN] OFF
ALTER TABLE [TAIKHOAN] ADD CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY ([TAIKHOAN_ID])
go




CREATE TABLE [LOP](
	[LOP_ID] NVARCHAR(50) NOT NULL PRIMARY KEY,
	[TENLOP] NVARCHAR(50),
)
INSERT[LOP]([LOP_ID],[TENLOP]) VALUES (N'E1.O5.02',N'Tòa E1 tầng 5 phòng 02')
INSERT[LOP]([LOP_ID],[TENLOP]) VALUES (N'E1.O5.03',N'Tòa E1 tầng 5 phòng 03')


CREATE TABLE [CHUDE] (
  [CHUDE_ID] INT IDENTITY(1,1) NOT NULL,
  [TENCHUDE] NVARCHAR(255) NOT NULL,
  [LOP_ID] NVARCHAR(50) NOT NULL,
  [SOCAUHOI] INT DEFAULT 0,
  [TIME] INT DEFAULT 0,
  [TAIKHOAN_ID] INT NOT NULL
)
ALTER TABLE [CHUDE] ADD CONSTRAINT [PK_CHUDE] PRIMARY KEY ([CHUDE_ID])
go
ALTER TABLE [CHUDE] ADD CONSTRAINT fk_CHUDE_LOP FOREIGN KEY ([LOP_ID]) REFERENCES [LOP] ([LOP_ID]);
ALTER TABLE [CHUDE] ADD CONSTRAINT fk_CHUDE_TAIKHOAN FOREIGN KEY ([TAIKHOAN_ID]) REFERENCES [TAIKHOAN] ([TAIKHOAN_ID]);
SET IDENTITY_INSERT [CHUDE] ON
INSERT [CHUDE] ([CHUDE_ID],[TENCHUDE],[LOP_ID],[SOCAUHOI],[TIME],[TAIKHOAN_ID])VALUES(1,N'Lập Trinh Mạng',N'E1.O5.02',4,30,1)
INSERT [CHUDE] ([CHUDE_ID],[TENCHUDE],[LOP_ID],[SOCAUHOI],[TIME],[TAIKHOAN_ID])VALUES(2,N'Lịch sử',N'E1.O5.02',4,30,2)
SET IDENTITY_INSERT [CHUDE] OFF


CREATE TABLE [BODE]
(
 [BODE_ID] Int IDENTITY(1,1) NOT NULL,
 [CHUDE_ID] INT NOT NULL,
 [NOIDUNG] Ntext NULL,
 [A] Ntext NULL,
 [B] Ntext NULL,
 [C] Ntext NULL,
 [D] Ntext NULL,
 [DAP_AN] Char(1) NULL
)
go
ALTER TABLE [BODE] ADD CONSTRAINT [PK_BODE] PRIMARY KEY ([BODE_ID])
go
ALTER TABLE [BODE] ADD CONSTRAINT fk_BODE_CHUDE FOREIGN KEY ([CHUDE_ID]) REFERENCES [CHUDE] ([CHUDE_ID]);
GO
SET IDENTITY_INSERT [BODE] ON
INSERT [BODE] ([BODE_ID],[CHUDE_ID],[NOIDUNG],[A],[B],[C],[D],[DAP_AN]) VALUES 
(1,1,N'Thiết bị hub thông thường nằm ở tầng nào của mô hình OSI?',N'Tầng 1',N'Tầng 2',N'Tầng 3',N'Tất cả đều sai ','A')
INSERT [BODE] ([BODE_ID],[CHUDE_ID],[NOIDUNG],[A],[B],[C],[D],[DAP_AN]) VALUES 
(2,1,N'2.Thiết bị hub thông thường nằm ở tầng nào của mô hình OSI?',N'Tầng 1',N'Tầng 2',N'Tầng 3',N'Tất cả đều sai ','A')
INSERT [BODE] ([BODE_ID],[CHUDE_ID],[NOIDUNG],[A],[B],[C],[D],[DAP_AN]) VALUES 
(3,1,N'3.Thiết bị hub thông thường nằm ở tầng nào của mô hình OSI?',N'Tầng 1',N'Tầng 2',N'Tầng 3',N'Tất cả đều sai ','A')
INSERT [BODE] ([BODE_ID],[CHUDE_ID],[NOIDUNG],[A],[B],[C],[D],[DAP_AN]) VALUES 
(4,1,N'4.Thiết bị hub thông thường nằm ở tầng nào của mô hình OSI?',N'Tầng 1',N'Tầng 2',N'Tầng 3',N'Tất cả đều sai ','A')
INSERT [BODE] ([BODE_ID],[CHUDE_ID],[NOIDUNG],[A],[B],[C],[D],[DAP_AN]) VALUES 
(5,1,N'5.Thiết bị hub thông thường nằm ở tầng nào của mô hình OSI?',N'Tầng 1',N'Tầng 2',N'Tầng 3',N'Tất cả đều sai ','A')
INSERT [BODE] ([BODE_ID],[CHUDE_ID],[NOIDUNG],[A],[B],[C],[D],[DAP_AN]) VALUES 
(6,1,N'6.Thiết bị hub thông thường nằm ở tầng nào của mô hình OSI?',N'Tầng 1',N'Tầng 2',N'Tầng 3',N'Tất cả đều sai ','A')
INSERT [BODE] ([BODE_ID],[CHUDE_ID],[NOIDUNG],[A],[B],[C],[D],[DAP_AN]) VALUES 
(7,1,N'7.Thiết bị hub thông thường nằm ở tầng nào của mô hình OSI?',N'Tầng 1',N'Tầng 2',N'Tầng 3',N'Tất cả đều sai ','A')
SET IDENTITY_INSERT [BODE] OFF


CREATE TABLE [CHUDE_TAIKHOAN] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [TAIKHOAN_ID] INT NOT NULL,
  [CHUDE_ID] INT NOT NULL,
  [SCORE] FLOAT DEFAULT NULL
)
ALTER TABLE [CHUDE_TAIKHOAN] ADD CONSTRAINT [PK_CHUDE_TAIKHOAN] PRIMARY KEY ([ID])
go
ALTER TABLE [CHUDE_TAIKHOAN] ADD CONSTRAINT fk_CHUDE_TAIKHOAN01 FOREIGN KEY ([CHUDE_ID]) REFERENCES [CHUDE] ([CHUDE_ID]);
GO
ALTER TABLE [CHUDE_TAIKHOAN] ADD CONSTRAINT fk_TAIKHOAN_CHUDE FOREIGN KEY ([TAIKHOAN_ID]) REFERENCES [TAIKHOAN] ([TAIKHOAN_ID]);
GO

